### ISSUE TITLE
[BUG] Не має вспливашки при логінізації

### ISSUE THREAD

**Issue by Dimk69** [serg-rsv/team-project-care-pets#131]
*****Describe the bug*****
При спробі увійти в систему не ввівши нічого у поля **Email** та **Password** нічого не відбувається!

*****To Reproduce*****
1.Зайти на сайт https://sk-care-pets.netlify.app/
2.Натиснути кнопку Login у верхньому правому куті.
3.Не ввівши значень натиснути на кнопку Login посередині екрану.

*****Expected result*****
З'являється модалка, де написано, що користувач ввів невалідні данні.

*****Actual result*****
Нічого не відбувається.

*****Desktop*****
- OS [ Windows 11 ]
- Browser [ Google Chrome 107.0.5304.107 ]

Wrote a bug report: Dmytro Polishchuk

**Comment by serg-rsv** [comment]
Вспливашки поки не реалізовані.

#154
