### ISSUE TITLE
[BUG] Не відображається назва породи тварини (підрозділ "Sell")				

### ISSUE THREAD

**Issue by NataliOsiichuk** [serg-rsv/team-project-care-pets#139]
**Describe the bug**
У списку оголошень тварин у підрозділі "Sell" не відображається назва породи тварини (слово "breed" є, а яка це порода не вказано)
			
**To Reproduce
Steps to reproduce:**
1. Відкрити сайт [Petly](https://sk-care-pets.netlify.app/notices/sell)
2. Перейти на тип оголошення "Sell".
3. 
**Expected result**
Відображається катeгорія "Breed" із назвою породи тарини.

**Actual result**
В оголошенні відображається катeгорія "Breed", але назви нема.

Desktop

OS [ mac OS ]
OS Version [ 13.0.1 ]
Browser [ Safari ]
Wrote a bug report: Nataliia Osiichuk

<img width="1533" alt="2" src="https://user-images.githubusercontent.com/118765069/203343914-3ace21b9-cdb9-4791-ad63-e89d96d48638.png">

**Comment by serg-rsv** [comment]
Все є, Наталі. То тестові оголошення з частково заповненими полями.

![image](https://user-images.githubusercontent.com/88489822/203426345-a71c6b77-6ab9-4c6a-918a-aa252144c87f.png)
