### ISSUE TITLE
[BUG] Імʼя тварин при кліку на "Learn more"

### ISSUE THREAD

**Issue by NataliOsiichuk** [serg-rsv/team-project-care-pets#144]
**Describe the bug**
Відсутнє імʼя тварин при кліку на "Learn more" (сама категорія є, а імені нема)

**To Reproduce**
**Steps to reproduce the behavior:**

1. Відкрити [сайт](https://sk-care-pets.netlify.app/notices)
2. Перейти до одного із підрозділів ("Sell"/ "Found/Lost"/ "In good hands")
3. Вибрати прешу тварину зі списку і клікнути на "Learn more"
4. Відкрилася модалка із повним описом вибраного оголошення.

**Expected result**
В модальці мітяться імʼя обраної тварини.

**Actual result**
В модальці нема імені (категорія "name" є!)

Desktop

OS [ mac OS ]
OS Version [ 13.0.1 ]
Browser [ Safari ]
Wrote a bug report: Nataliia Osiichuk

<img width="1135" alt="6 1" src="https://user-images.githubusercontent.com/118765069/203364967-e8641f3a-c8b8-461c-9a1c-ec92516d7267.png">

<img width="1135" alt="6 2" src="https://user-images.githubusercontent.com/118765069/203365018-a16df41d-c022-4974-8503-33d296450189.png">

<img width="1135" alt="6 3" src="https://user-images.githubusercontent.com/118765069/203365089-c65b70ae-8d80-4586-8a61-ca85e5d5d3a1.png">

**Comment by serg-rsv** [comment]
![image](https://user-images.githubusercontent.com/88489822/203424815-e637488f-bd48-4cab-8246-dda6c7c3a78a.png)
