### ISSUE TITLE
[BUG] Імʼя користувача при кліку на "Learn more"

### ISSUE THREAD

**Issue by NataliOsiichuk** [serg-rsv/team-project-care-pets#148]
**Describe the bug**
При кліку на "Learn more" має бути також додаткова категорія "Імʼя користувача", який зробив публікацію

**To Reproduce
Steps to reproduce the behavior:**

1. Відкрити [сайт](https://sk-care-pets.netlify.app/notices)
2. Перейти до одного із підрозділів ("Sell"/ "Found/Lost"/ "In good hands")
3. Вибрати будь-яку тварину зі списку і клікнути на "Learn more"
4. Відкрилася модалка із повним описом вибраного оголошення.

**Expected result**
В модальному вікні міститься інформація про користувача, який зробив публікацію.

Actual result
В модальці нема такої категорії "Імʼя користувача".

Desktop

OS [ mac OS ]
OS Version [ 13.0.1 ]
Browser [ Safari ]
Wrote a bug report: Nataliia Osiichuk

<img width="834" alt="10" src="https://user-images.githubusercontent.com/118765069/203382389-fcd3bf36-0276-4e08-8b8e-d8d8f055a7fc.png">

**Comment by serg-rsv** [comment]
На макеті відсутнє дане поле.
