### ISSUE TITLE
Створити нотіфікашки для обробки помилок при запиті до сервера

### ISSUE THREAD

**Issue by serg-rsv** [serg-rsv/team-project-care-pets#154]
Можна використати бібліотеку [react-toastify](https://www.npmjs.com/package/react-toastify)
Наприклад помилки:
- Помилка під час логіну. Невірний логін/пароль.
- Помилка під час реєстрації. Такий імейл вже використовується.

При успішних діях:
- Оголошення створено
- Домашній улюбленець доданий до списку

**Comment by Nikolay-Tymoshchuk** [comment]
І не лише помилок!=)
