### ISSUE TITLE
Не працює іконка "Done" при створенні картки з твариною у особистому кабинеті

### ISSUE THREAD

**Issue by Dzulion** [serg-rsv/team-project-care-pets#156]
Describe the bug
Не працює іконка "Done" при створенні картки з твариною у особистому кабинеті

To Reproduce
Steps to reproduce:

Відкрити сайт [Petly](https://sk-care-pets.netlify.app);
Увійти до особистого кабинету;

Клікнути на значок "Add pet";
Заповнюємо дані тварини.
Expected result
При кліку на "Done" у особистому кабинеті добавляється карта тварини.

Actual result
Іконка "Done" не клікабельна. 

Desktop

OS [ Windows 10 ]
Browser [ WaveBrowser]
Wrote a bug report: Oleksii Dzuiba

**Comment by Dzulion** [comment]
![image](https://user-images.githubusercontent.com/118855549/203426254-f2002a51-3460-4290-9b53-1638c43df564.png)

**Comment by Dzulion** [comment]
![image](https://user-images.githubusercontent.com/118855549/203426366-610d5a36-ee34-4317-96d8-51fa464cca0e.png)

**Comment by serg-rsv** [comment]
Виправити валідацію форми для роботи з кирилицею.
