### ISSUE TITLE
Не працює видалєння картки тварини у особистому кабинеті

### ISSUE THREAD

**Issue by Dzulion** [serg-rsv/team-project-care-pets#163]
Describe the bug
Не працює іконка видалєння картки тварини у особистому кабинеті

To Reproduce
Steps to reproduce:
Відкрити сайт [Petly](https://sk-care-pets.netlify.app/);
Увійти до особистого кабинету;
На картоці своєї тварини клікнути на значок видалення.

Expected result
При кліку на значок видалення, зявляється попереджувальне вікно. Після підтвердження картка тварини видаляється.

Actual result
Зявляється попереджувальне вікно, відсутні клавіши погоджування.

Desktop

OS [ Windows 10 ]
Browser [ WaveBrowser]
Wrote a bug report: Oleksii Dzuiba

**Comment by Dzulion** [comment]
![image](https://user-images.githubusercontent.com/118855549/203657202-6ea96010-4f20-490e-8961-e153f76e6760.png)
![image](https://user-images.githubusercontent.com/118855549/203657251-38e2457d-1de3-4ca6-989d-efa9aa97c7a4.png)

**Comment by serg-rsv** [comment]
Цей баг вже виправили. Перевірте після оголошення про оновлення продакшну.
