### ISSUE TITLE
Картка My information у розділі "місто, область" відсутній drop-down список для вибору мicта

### ISSUE THREAD

**Issue by Dzulion** [serg-rsv/team-project-care-pets#164]
Describe the bug
Картка My information (у особистому кабинеті) у полі: місто, область повинна бути іконкa редагування з drop-down список для вибору мicта

To Reproduce
Steps to reproduce:
Відкрити сайт [Petly](https://sk-care-pets.netlify.app/);
Увійти до особистого кабинету;

На картці My information у розділі " City" клікаємо на іконку редагування.

Expected result
При кліку на іконку редагування повине зявитися drop-down список для вибору мicта .

Actual result
Зявляється можливість лише самостійного змінення тексту у розділі.

Desktop

OS [ Windows 10 ]
Browser [ WaveBrowser]
Wrote a bug report: Oleksii Dzuiba

**Comment by Dzulion** [comment]
![image](https://user-images.githubusercontent.com/118855549/203659196-5f81aeb8-54d5-4d18-b1c0-929645416170.png)
![image](https://user-images.githubusercontent.com/118855549/203659252-4a77170f-246e-4e74-8b5d-a94d8b468f65.png)

**Comment by serg-rsv** [comment]
Цей функціонал не передбачений в ТЗ.
В нашому випадку ці дані вводяться вручну.
