### ISSUE TITLE
[BUG] Не працює кнопка пошуку (лупа)

### ISSUE THREAD

**Issue by NataliOsiichuk** [serg-rsv/team-project-care-pets#203]
**Describe the bug**
Не працює лупа у рядку для пошуку тварин

**To Reproduce
Steps to reproduce the behavior:**

1. Відкрити [сайт](https://sk-care-pets.netlify.app/notices)
2. Перейти до будь-якого підрозділу ("Продається"/ "Знайшов/Загубив"/ "У добрі руки").
3. У рядку для пошуку тварин вписати якесь слово.
4. Клікнути на значок 🔍 вкінці пошукого рядка.

**Expected result**
Відкривається результат пошуку.

**Actual result**
Значок 🔍 не працює.

Desktop

OS [ mac OS ]
OS Version [ 13.0.1 ]
Browser [ Safari ]
Wrote a bug report: Nataliia Osiichuk

<img width="1466" alt="20" src="https://user-images.githubusercontent.com/118765069/204099294-cf43134f-c380-46ef-b7d7-552fb4eab6cf.png">

**Comment by serg-rsv** [comment]
Зробити декоративний елемент функціональною кнопкою.
